-- ============================================================
-- Mazed Auto — DB diagnostic
--
-- Paste this whole file into the Supabase SQL editor and run.
-- Each row tells you whether a feature is in place. "MISSING"
-- means you still need to apply the corresponding migration.
-- Safe to run anytime; reads only.
--
-- The DO block runs the count-based seed checks via EXECUTE so
-- missing tables don't blow up the whole query.
-- ============================================================

drop table if exists _diag;
create temp table _diag (
  ord     int generated by default as identity,
  feature text,
  ok      boolean
);

insert into _diag (feature, ok) values
  -- ───────── schema ─────────
  ('schema · auctions table',           to_regclass('public.auctions')      is not null),
  ('schema · sellers table',            to_regclass('public.sellers')       is not null),
  ('schema · bids table',               to_regclass('public.bids')          is not null),
  ('schema · transactions table',       to_regclass('public.transactions')  is not null),
  ('schema · notifications table',      to_regclass('public.notifications') is not null),

  -- ───────── pre-existing migrations ─────────
  ('platform_settings table',           to_regclass('public.platform_settings') is not null),
  ('kyc_submissions table',             to_regclass('public.kyc_submissions')   is not null),
  ('auto_bids table',                   to_regclass('public.auto_bids')         is not null),
  ('conversations table',               to_regclass('public.conversations')     is not null),
  ('auction_forfeits table',            to_regclass('public.auction_forfeits')  is not null),
  ('user_activity_log table',           to_regclass('public.user_activity_log') is not null),
  ('is_admin() helper',                 exists(select 1 from pg_proc where proname='is_admin')),
  ('review_kyc() RPC',                  exists(select 1 from pg_proc where proname='review_kyc')),
  ('admin_adjust_trust() RPC',          exists(select 1 from pg_proc where proname='admin_adjust_trust')),
  ('finalize_auction() RPC',            exists(select 1 from pg_proc where proname='finalize_auction')),
  ('end_expired_auctions() RPC',        exists(select 1 from pg_proc where proname='end_expired_auctions')),
  ('forfeit_winner_deposit() RPC',      exists(select 1 from pg_proc where proname='forfeit_winner_deposit')),

  -- ───────── new: admin foundations ─────────
  ('admin_audit_log table',             to_regclass('public.admin_audit_log') is not null),
  ('admin_sessions table',              to_regclass('public.admin_sessions')  is not null),
  ('admin_role() helper',               exists(select 1 from pg_proc where proname='admin_role')),
  ('has_admin_capability() helper',     exists(select 1 from pg_proc where proname='has_admin_capability')),
  ('log_admin_action() helper',         exists(select 1 from pg_proc where proname='log_admin_action')),

  -- ───────── new: admin actions ─────────
  ('user_warnings table',               to_regclass('public.user_warnings')        is not null),
  ('user_bans table',                   to_regclass('public.user_bans')            is not null),
  ('auction_edit_requests table',       to_regclass('public.auction_edit_requests') is not null),
  ('contact_messages table',            to_regclass('public.contact_messages')     is not null),
  ('admin_broadcasts table',            to_regclass('public.admin_broadcasts')     is not null),
  ('admin_warn_user() RPC',             exists(select 1 from pg_proc where proname='admin_warn_user')),
  ('admin_ban_user() RPC',              exists(select 1 from pg_proc where proname='admin_ban_user')),
  ('admin_force_cancel_auction() RPC',  exists(select 1 from pg_proc where proname='admin_force_cancel_auction')),
  ('admin_force_seller_decision() RPC', exists(select 1 from pg_proc where proname='admin_force_seller_decision')),
  ('admin_void_transaction() RPC',      exists(select 1 from pg_proc where proname='admin_void_transaction')),

  -- ───────── new: financial ─────────
  ('payouts table',                     to_regclass('public.payouts') is not null),
  ('admin_create_payout() RPC',         exists(select 1 from pg_proc where proname='admin_create_payout')),

  -- ───────── new: users-list ─────────
  ('admin_list_users() RPC',            exists(select 1 from pg_proc where proname='admin_list_users')),
  ('admin_get_user() RPC',              exists(select 1 from pg_proc where proname='admin_get_user')),

  -- ───────── new: CMS ─────────
  ('cms_pages table',                   to_regclass('public.cms_pages')          is not null),
  ('cms_faqs table',                    to_regclass('public.cms_faqs')           is not null),
  ('cms_promo_banners table',           to_regclass('public.cms_promo_banners')  is not null),
  ('cms_brands table',                  to_regclass('public.cms_brands')         is not null),
  ('cms_features table',                to_regclass('public.cms_features')       is not null),
  ('cms_cities table',                  to_regclass('public.cms_cities')         is not null),

  -- ───────── new: notifications expansion ─────────
  ('notification_templates table',      to_regclass('public.notification_templates') is not null),
  ('user_notification_prefs table',     to_regclass('public.user_notification_prefs') is not null),
  ('should_notify() helper',            exists(select 1 from pg_proc where proname='should_notify')),
  ('notify_with_template() helper',     exists(select 1 from pg_proc where proname='notify_with_template')),
  ('notifications.kind CHECK accepts kyc_approved',
    exists(
      select 1 from pg_constraint c
       where c.conname = 'notifications_kind_check'
         and pg_get_constraintdef(c.oid) ilike '%kyc_approved%'
    )),

  -- ───────── new: settings approval ─────────
  ('propose_setting_value() RPC',       exists(select 1 from pg_proc where proname='propose_setting_value')),
  ('approve_pending_setting() RPC',     exists(select 1 from pg_proc where proname='approve_pending_setting')),

  -- ───────── new: admin team / messaging / ownership / fraud / analytics ─────────
  ('admin_list_admins() RPC',           exists(select 1 from pg_proc where proname='admin_list_admins')),
  ('admin_set_role() RPC',              exists(select 1 from pg_proc where proname='admin_set_role')),
  ('admin_list_conversations() RPC',    exists(select 1 from pg_proc where proname='admin_list_conversations')),
  ('admin_read_conversation() RPC',     exists(select 1 from pg_proc where proname='admin_read_conversation')),
  ('auctions.ownership_exception column',
    exists(
      select 1 from information_schema.columns
       where table_schema='public' and table_name='auctions'
         and column_name='ownership_exception'
    )),
  ('fraud_duplicate_phones() RPC',      exists(select 1 from pg_proc where proname='fraud_duplicate_phones')),
  ('fraud_rapid_bidders() RPC',         exists(select 1 from pg_proc where proname='fraud_rapid_bidders')),
  ('analytics_funnel() RPC',            exists(select 1 from pg_proc where proname='analytics_funnel')),
  ('analytics_top_sellers() RPC',       exists(select 1 from pg_proc where proname='analytics_top_sellers')),
  ('analytics_bidding_heatmap() RPC',   exists(select 1 from pg_proc where proname='analytics_bidding_heatmap')),

  -- ───────── new: Sprint A ─────────
  ('auction_status_log table',           to_regclass('public.auction_status_log') is not null),
  ('admin_edit_auction() RPC',           exists(select 1 from pg_proc where proname='admin_edit_auction')),
  ('admin_reset_email_verification() RPC', exists(select 1 from pg_proc where proname='admin_reset_email_verification')),
  ('admin_reset_phone_verification() RPC', exists(select 1 from pg_proc where proname='admin_reset_phone_verification')),
  ('admin_bulk_review_kyc() RPC',        exists(select 1 from pg_proc where proname='admin_bulk_review_kyc')),
  ('admin_bulk_approve_auctions() RPC',  exists(select 1 from pg_proc where proname='admin_bulk_approve_auctions')),
  ('admin_bulk_reject_auctions() RPC',   exists(select 1 from pg_proc where proname='admin_bulk_reject_auctions')),
  ('admin_dm_user() RPC',                exists(select 1 from pg_proc where proname='admin_dm_user')),
  ('admin_refund_deposit() RPC',         exists(select 1 from pg_proc where proname='admin_refund_deposit')),
  ('admin_self_summary() RPC',           exists(select 1 from pg_proc where proname='admin_self_summary'));

-- Count-based seed checks — wrapped in DO so missing tables don't crash.
-- Each EXECUTE runs only if the table exists.
do $$
declare
  v_n bigint;
begin
  if to_regclass('public.platform_settings') is not null then
    execute 'select count(*) from public.platform_settings' into v_n;
    insert into _diag (feature, ok)
    values (format('platform_settings · seeded (%s rows ≥ 27)', v_n), v_n >= 27);

    -- Specific keys
    insert into _diag (feature, ok) values
      ('settings · listing.duration_options',
        exists(select 1 from public.platform_settings where key='listing.duration_options')),
      ('settings · listing.bid_increment_tiers',
        exists(select 1 from public.platform_settings where key='listing.bid_increment_tiers')),
      ('settings · support.email',
        exists(select 1 from public.platform_settings where key='support.email')),
      ('settings · trust.tier_thresholds',
        exists(select 1 from public.platform_settings where key='trust.tier_thresholds')),
      ('settings · media.image.max_edge_px',
        exists(select 1 from public.platform_settings where key='media.image.max_edge_px')),
      ('settings · system.maintenance_mode',
        exists(select 1 from public.platform_settings where key='system.maintenance_mode'));
  end if;

  if to_regclass('public.cms_brands') is not null then
    execute 'select count(*) from public.cms_brands' into v_n;
    insert into _diag (feature, ok)
    values (format('cms_brands · seeded (%s rows ≥ 13)', v_n), v_n >= 13);
  end if;

  if to_regclass('public.cms_cities') is not null then
    execute 'select count(*) from public.cms_cities' into v_n;
    insert into _diag (feature, ok)
    values (format('cms_cities · seeded (%s rows ≥ 20)', v_n), v_n >= 20);
  end if;

  if to_regclass('public.notification_templates') is not null then
    execute 'select count(*) from public.notification_templates' into v_n;
    insert into _diag (feature, ok)
    values (format('notification_templates · seeded (%s rows ≥ 36)', v_n), v_n >= 36);
  end if;
end $$;

select
  case when ok then '✓' else '✗ MISSING' end as status,
  feature
from _diag
order by ok asc, ord asc;
