// Auto-generated by scripts/optimize-splash.mjs.
// Tiny 24-pixel-wide blurred preview of /public/loading.jpg, inlined
// here so the splash background paints with the first HTML byte —
// before /loading.webp finishes downloading. Re-run the script if you
// swap the splash asset.

export const SPLASH_LQIP = "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAzABgDASIAAhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAEDBAIFBv/EAB8QAAICAQUBAQAAAAAAAAAAAAABAhEDBBIhMUFxgf/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABkRAQACAwAAAAAAAAAAAAAAAAABQQIREv/aAAwDAQACEQMRAD8A+MOkclkI2wCjfILMlQjXoIKI9noaXQZs0ITjtjGU9ic3X78MGNqMrdmxa7IkksrpO6aT668Jl1Sxq2fLxNq06dAjJPfNy9fYNIqRNkACQQAAAAkAAf/Z";
