/**
 * What a notification IS, in one place.
 *
 * The old system spread this over three files that disagreed with each other:
 * a link map in target.ts, an icon switch in NotificationBell.tsx, and a
 * separate SMS list in sms-kinds.ts. Adding an event meant editing three
 * places and forgetting one — which is how `listing_published` ended up
 * pointing at "/sell", a route that now redirects to the BLANK publish form.
 * A seller told "your annonce is online" was taken to an empty form.
 *
 * The audit that produced this file, against the live database:
 *
 *   • 1 372 notifications, 1 355 unread. 1 240 of them are two machine kinds
 *     (auction_ended_unsold, auction_live_seller) generated by the relisting
 *     loop, about auctions that no longer exist.
 *   • Every kind with any volume is auction-era. Not one listing_* row has
 *     ever been written.
 *   • The single event this product is built around — a buyer revealing a
 *     seller's phone number — notifies nobody at all.
 *   • Dead destinations: /kyc/status (feature deleted), /admin/kyc-queue,
 *     /account/inspections, /sell#payouts, and every /auctions/<id> link now
 *     that the auctions are gone.
 *
 * So: one catalogue. Each kind declares who it is for, how it looks, where it
 * goes (from its own payload), and whether it is worth an SMS. Anything not
 * listed here is legacy — it still renders, quietly, and links home.
 */

export type NotificationAudience = "seller" | "buyer" | "admin";
export type NotificationTone = "good" | "bad" | "warn" | "info";

export type NotificationPayload = {
  listing_id?: string;
  listing_title?: string;
  payment_id?: string;
  [key: string]: unknown;
};

export type NotificationKindDef = {
  /** Icon name, resolved to a lucide component by the renderer. */
  icon:
    | "phone"
    | "check"
    | "x"
    | "clock"
    | "receipt"
    | "megaphone"
    | "sparkles"
    | "wrench"
    | "bell";
  tone: NotificationTone;
  audience: NotificationAudience;
  /** Short label above the title in the list. */
  label: string;
  /**
   * Where tapping it should land. Takes the row's payload and its stored
   * `link` column: enqueue_notification has no payload parameter, so most rows
   * carry their entity in the link and nothing else.
   */
  href: (p: NotificationPayload, link?: string | null) => string;
  /**
   * Worth interrupting someone's day by SMS. Deliberately short: an SMS costs
   * money and attention, so it is reserved for things that are time-bound or
   * that make the seller money.
   */
  sms?: boolean;
};

const LISTING_LINK = /^\/annonces\/[0-9a-fA-F-]{36}$/;

const listingHref = (p: NotificationPayload, link?: string | null) =>
  p.listing_id
    ? `/annonces/${p.listing_id}`
    : link && LISTING_LINK.test(link)
      ? link
      : "/account/listings";

export const NOTIFICATION_KINDS: Record<string, NotificationKindDef> = {
  // ── No longer sent ──────────────────────────────────────────────────────
  // Nothing enqueues this any more: the ping on every "afficher le numéro"
  // was removed on request. The kind stays defined because notifications sent
  // before that still sit in people's lists and need a label and an icon to
  // render — deleting it here would turn those rows into blanks.
  //
  // The reveal itself is still recorded in `contact_reveals`, still counted on
  // the annonce, and still shown in the admin statistics.
  contact_revealed: {
    icon: "phone",
    tone: "good",
    audience: "seller",
    label: "Nouveau contact",
    href: listingHref,
    sms: true,
  },

  // ── Seller · the life of an annonce ─────────────────────────────────────
  listing_submitted: {
    icon: "clock",
    tone: "info",
    audience: "seller",
    label: "Annonce envoyée",
    href: () => "/account/listings",
  },
  listing_payment_received: {
    icon: "receipt",
    tone: "good",
    audience: "seller",
    label: "Paiement validé",
    href: () => "/account/listings",
  },
  listing_published: {
    icon: "check",
    tone: "good",
    audience: "seller",
    label: "Annonce en ligne",
    href: listingHref,
    sms: true,
  },
  listing_approved: {
    icon: "check",
    tone: "good",
    audience: "seller",
    label: "Annonce validée",
    href: listingHref,
  },
  listing_rejected: {
    icon: "x",
    tone: "bad",
    audience: "seller",
    label: "Annonce refusée",
    href: () => "/account/listings",
    sms: true,
  },
  listing_expiring: {
    icon: "clock",
    tone: "warn",
    audience: "seller",
    label: "Bientôt expirée",
    href: () => "/account/listings",
    sms: true,
  },
  listing_expired: {
    icon: "clock",
    tone: "warn",
    audience: "seller",
    label: "Annonce expirée",
    href: () => "/account/listings",
  },

  // ── Money ───────────────────────────────────────────────────────────────
  payment_accepted: {
    icon: "receipt",
    tone: "good",
    audience: "seller",
    label: "Paiement accepté",
    href: () => "/account/payments",
  },
  payment_rejected: {
    icon: "x",
    tone: "bad",
    audience: "seller",
    label: "Reçu refusé",
    href: () => "/account/payments",
    sms: true,
  },
  payment_receipt_received: {
    icon: "receipt",
    tone: "info",
    audience: "seller",
    label: "Reçu reçu",
    href: () => "/account/payments",
  },

  // ── From us ─────────────────────────────────────────────────────────────
  announcement: { icon: "megaphone", tone: "info", audience: "buyer", label: "Information", href: () => "/" },
  maintenance: { icon: "wrench", tone: "warn", audience: "buyer", label: "Maintenance", href: () => "/" },
  welcome: { icon: "sparkles", tone: "info", audience: "buyer", label: "Bienvenue", href: () => "/annonces" },

  // ── Admin queues ────────────────────────────────────────────────────────
  admin_listing_pending: {
    icon: "clock",
    tone: "warn",
    audience: "admin",
    label: "À modérer",
    href: () => "/admin/annonces",
  },
  admin_receipt_pending: {
    icon: "receipt",
    tone: "warn",
    audience: "admin",
    label: "Reçu à vérifier",
    href: () => "/admin/payments",
  },
};

/** Everything the renderer needs, including for a kind we no longer send. */
export function describeKind(kind: string): NotificationKindDef {
  return (
    NOTIFICATION_KINDS[kind] ?? {
      icon: "bell",
      tone: "info",
      audience: "buyer",
      label: "Notification",
      // A legacy row (an auction that no longer exists, a KYC page that was
      // deleted) must never strand the user on a 404: home, not its old link.
      href: () => "/",
    }
  );
}

/** The destination for a row, ignoring any stale `link` column it carries. */
export function notificationHref(
  kind: string,
  payload: NotificationPayload | null | undefined,
  storedLink?: string | null,
): string {
  const known = NOTIFICATION_KINDS[kind];
  if (known) return known.href(payload ?? {}, storedLink);
  // Unknown kind: trust the stored link only if it points somewhere that still
  // exists. /auctions, /kyc, /sell and /properties were all removed or
  // repurposed by the v3 pivot.
  if (storedLink && !/^\/(auctions|kyc|properties|sell|inspector)/.test(storedLink)) {
    return storedLink;
  }
  return "/";
}

/** Kinds that justify an SMS. */
export const SMS_KINDS: string[] = Object.entries(NOTIFICATION_KINDS)
  .filter(([, def]) => def.sms)
  .map(([kind]) => kind);
