// One-off: turn /public/loading.jpg into a smaller WebP + a tiny base64
// LQIP we can inline in HTML for an instant first paint. Run once
// after any redesign of the splash asset.
//
//   node scripts/optimize-splash.mjs
//
// Outputs:
//   public/loading.webp     — primary, ~30-40 KB
//   public/loading.jpg      — kept as fallback for ancient browsers
//   src/components/layout/splash-lqip.ts — tiny 24w base64 string

import sharp from "sharp";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_DIR = resolve(__dirname, "..");
const SRC = resolve(WEB_DIR, "public/loading.jpg");
const OUT_WEBP = resolve(WEB_DIR, "public/loading.webp");
const OUT_LQIP = resolve(WEB_DIR, "src/components/layout/splash-lqip.ts");

const srcBuf = readFileSync(SRC);
console.log("✓  Source loading.jpg     :", (srcBuf.length / 1024).toFixed(0), "KB");

// 1) Modern WebP — same dimensions as the source so the layout
//    doesn't reflow when the browser swaps from LQIP → real splash.
const webpBuf = await sharp(srcBuf)
  .webp({ quality: 78, effort: 6 })
  .toBuffer();
writeFileSync(OUT_WEBP, webpBuf);
console.log(
  `✓  loading.webp           : ${(webpBuf.length / 1024).toFixed(0)} KB  (was ${(srcBuf.length / 1024).toFixed(0)} KB)`,
);

// 2) LQIP — a tiny 24-pixel-wide JPEG, blurred. Inlined as base64 so
//    it lives in the HTML itself and paints with the first frame. CSS
//    blurs it visually so 24×N pixels look like a smooth backdrop, not
//    a pixelated thumbnail.
const lqipBuf = await sharp(srcBuf)
  .resize({ width: 24 })
  .jpeg({ quality: 40 })
  .toBuffer();
const dataUrl = `data:image/jpeg;base64,${lqipBuf.toString("base64")}`;
writeFileSync(
  OUT_LQIP,
  `// Auto-generated by scripts/optimize-splash.mjs.
// Tiny 24-pixel-wide blurred preview of /public/loading.jpg, inlined
// here so the splash background paints with the first HTML byte —
// before /loading.webp finishes downloading. Re-run the script if you
// swap the splash asset.

export const SPLASH_LQIP = "${dataUrl}";
`,
);
console.log(
  `✓  splash-lqip.ts          : ${(lqipBuf.length / 1024).toFixed(1)} KB inline (${dataUrl.length} chars base64)`,
);

console.log("\nNext: update SplashScreen.tsx + globals.css to use both.");
