-- ============================================================================
-- A reference you can say out loud.
--
-- Every annonce is identified by a uuid. That is correct for machines and
-- useless for people: nobody reads "181e961b-92a7-4b36-9ce5-78906c23c470" down
-- a phone line, and an admin looking for the car a seller just called about
-- has nothing to search by except a title that may be "Golf 2024" on thirty
-- rows.
--
-- MZ-00042. Five digits, no ambiguous characters, sortable, and short enough
-- to write on a receipt or read to a caller.
--
-- Generated by a BEFORE INSERT trigger rather than a column DEFAULT so that
-- an explicit value (a data import, a restore) is respected instead of being
-- overwritten, and so the sequence is only consumed when it is actually used.
-- ============================================================================

create sequence if not exists public.listing_reference_seq as bigint start 1;

create or replace function public.listing_reference_next()
returns text
language sql
volatile
set search_path = public
as $$
  select 'MZ-' || lpad(nextval('public.listing_reference_seq')::text, 5, '0');
$$;

alter table public.listings
  add column if not exists reference text;

-- Backfill in creation order, so the oldest annonce is MZ-00001 and the
-- numbers tell you something about age.
do $$
declare r record;
begin
  for r in select id from public.listings where reference is null order by created_at, id loop
    update public.listings set reference = public.listing_reference_next() where id = r.id;
  end loop;
end $$;

create or replace function public.listings_set_reference()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.reference is null or btrim(new.reference) = '' then
    new.reference := public.listing_reference_next();
  end if;
  return new;
end;
$$;

drop trigger if exists set_listing_reference on public.listings;
create trigger set_listing_reference
  before insert on public.listings
  for each row execute function public.listings_set_reference();

-- Unique, and indexed for the admin's search box.
create unique index if not exists listings_reference_uniq
  on public.listings (reference);

alter table public.listings
  alter column reference set not null;

comment on column public.listings.reference is
  'Human-readable public reference (MZ-00042). Shown on the annonce and searchable in the admin.';
